help_file = {
    'server': 'Configure the world the bot should play on',
    'server.server': 'The server endpoint to use (the world)',
    'server.endpoint': 'Endpoint server to use (the full url)',
    'server.server_on_twstats': 'Is the server listed on twstats.com?',
    'reporting': 'Enable advanced reporting features',
    'reporting.enabled': 'Enable the reporting feature',
    'reporting.connection_string': 'Could be of type file://filename or mysql://user:password@host:port/database_name',
    'bot': 'Set global bot configuration variables',
    'bot.active_hours': 'The hours when the bot should be active, e.g. "6-23" (does not impact attack timings)',
    'bot.delay_factor': 'Delay factor to use — 5-7 seconds * delay factor (very low factors will probably cause ban)',
    'bot.active_delay': 'Delay in seconds to use during active hours',
    'bot.inactive_delay': 'Delay in seconds to use during inactive hours',
    'bot.inactive_still_active': 'When disabled, stops the bot from running during inactive hours',
    'bot.add_new_villages': 'Automatically add the default village config to newly conquered villages',
    'bot.village_name_template': 'Template to use for new villages — use {num} to set the config index as name',
    'bot.village_name_number_length': 'The number length — lower values will be prefixed with zeroes',
    'bot.auto_set_village_names': 'Automatically set village names based on the template',
    'bot.user_agent': 'Set this to the browser agent your session is using (mismatch may cause ban)',
    'building': 'Automatic construction of buildings',
    'building.manage_buildings': 'Automatically manage buildings',
    'building.default': 'The default build template to use — village configs override this',
    'building.max_lookahead': 'Max number of items in queue to check before stopping',
    'building.max_queued_items': 'Max queued items (default: 2, premium: 5)',
    'units': 'Automatic recruitment and upgrade of units',
    'units.recruit': 'Automatically recruit units',
    'units.upgrade': 'Automatically upgrade units (level 1-3 and 1-10 smith systems)',
    'units.default': 'Default template for unit recruitment (templates/troops)',
    'units.batch_size': 'Amount of units to attempt to create per run — increase in late-game',
    'units.manage_defence': 'Manage defence distribution between villages (experimental)',
    'units.remove_manual_queued': 'Remove manually queued recruitment entries',
    'units.randomize_unit_queue': 'Randomize unit queue for a wider variety of units',
    'farms': 'Automatic farming of nearby (barbarian) villages',
    'farms.farm': 'Enable automatic farming',
    'farms.min_points': 'Minimum points of villages to attack',
    'farms.max_points': 'Maximum points of villages to attack',
    'farms.find_player_owned': 'Automatically attack all player-owned villages (dangerous)',
    'farms.search_radius': 'Max radius of villages to attack (fields)',
    'farms.default_away_time': 'Default cooldown in seconds before attacking a village again',
    'farms.full_loot_away_time': 'Cooldown for villages with high resource gain',
    'farms.low_loot_away_time': 'Cooldown for villages with low resource gain',
    'farms.max_farms': 'Number of nearby villages to check for farming',
    'farms.attack_higher_points': 'If disabled, villages with higher points than the current one are ignored',
    'farms.force_scout_if_available': 'Only attack villages that have been attacked before or scouted first',
    'farms.farm_scout_amount': 'Number of spies used to scout a village before farming',
    'market': 'Automatic management of public market trading (offer system)',
    'market.auto_trade': 'Enable automated public market trading',
    'market.max_trade_duration': 'Max duration of public trade offers (hours)',
    'market.auto_remove': 'Automatically remove existing or expired trade offers',
    'market.trade_multiplier': 'Enable uneven trade ratios (if supported by the world)',
    'market.trade_multiplier_value': 'Trade multiplier value — lower means more gain',
    'market.trade_max_per_hour': 'Max number of trades the bot can do in 1 hour',
    'resource_sharing': 'Automatic direct resource transfer between your own villages (Feature 9)',
    'resource_sharing.enabled': 'Enable automatic resource sharing between managed villages',
    'resource_sharing.threshold_pct': 'Percentage of storage capacity above which a village is considered a donor (e.g. 80 = 80%)',
    'resource_sharing.priority': 'Priority mode for resource distribution — "new_villages" sends to recently conquered villages first',
    'conquest': 'Automated barbarian village conquest (Feature 8)',
    'conquest.enabled': 'Enable automated conquest — activate only when nobles are available',
    'conquest.target': 'Conquest target type — currently supports "barbarian"',
    'conquest.max_radius': 'Maximum radius in fields to search for conquest targets',
    'conquest.priority': 'Target selection priority — "fill_gaps" scores by centrality, distance and points',
    'conquest.min_points': 'Minimum points a target village must have to be considered',
    'conquest.max_points': 'Maximum points a target village can have to be considered',
    'conquest.loyalty_regen_per_hour': 'Loyalty regeneration rate per hour (default: 1.5)',
    'conquest.loyalty_drop_per_noble': 'Loyalty reduction per noble hit — adjust based on world research (20-35)',
    'conquest.escort_ratio': 'Fraction of available troops to send as noble train escort (e.g. 0.5 = 50%)',
    'conquest.min_escort': 'Minimum escort units per unit type (optional override)',
    'inheritance': 'Config inheritance mode for newly conquered villages (Feature 6)',
    'inheritance.mode': 'Inheritance mode: "empire_ratio" (profile-aware), "nearest_village" (closest donor), "global_template" (original behaviour)',
    'empire': 'Empire-wide offensive/defensive village ratio (Feature 7)',
    'empire.offensive_ratio': 'Target number of offensive villages per defensive village (e.g. 3 means 3 offensive for every 1 defensive)',
    'empire.defensive_ratio': 'Target number of defensive villages (usually 1)',
    'world': 'World-specific feature flags',
    'world.knight_enabled': 'The world has knights enabled',
    'world.flags_enabled': 'Allows automatic management of flags (upgrading and defence)',
    'world.quests_enabled': 'World has quests enabled (bot will automatically finish them)',
    'world.trade_for_premium': 'World has the premium market enabled (doing this too much could result in ban)',
    'world.archers_enabled': 'Are archers / marchers enabled on the world',
    'world.building_destruction_enabled': 'Are rams / catapults enabled on the world',
    'village_template': 'Default template applied to all newly managed villages',
    'village.building': 'Override build template for this village',
    'village.units': 'Override recruitment / farm template for this village',
    'village.managed': 'This village should be managed by the bot',
    'village.active_hours': 'Active hours override for this village (e.g. "8-22") — null uses global setting',
    'village.profile': 'Village combat profile: "offensive" or "defensive" — set automatically by empire ratio',
    'village.scout_first': 'Scout villages before farming them',
    'village.additional_farms': 'List of village IDs to include in the farming process',
    'village.prioritize_building': 'Do not recruit if the builder does not have enough resources',
    'village.prioritize_snob': 'Do not recruit if the noble queue does not have enough resources',
    'village.trade_for_premium': 'Trade left-over resources for premium points (requires global option)',
    'village.gather_enabled': 'Use left-over units to gather additional resources',
    'village.gather_selection': 'The gather operation to perform (must be unlocked first)',
    'village.snobs': 'Number of nobles to maintain in this village',
    'village.evacuate_fragile_units_on_attack': 'Automatically evacuate fragile units (axe, noble) to nearby safe villages when under attack',
    'village.support_others': 'Allow sending automatic support to allied villages',
    'village.support_others_factor': 'Fraction of defensive units to use in support operations',
    'village.support_others_max_villages': 'Max number of villages to send support to',
    'village.request_support_on_attack': 'Automatically request support units when under attack',
    'village.conquest_enabled': 'Enable conquest actions from this village — overrides global conquest.enabled',
    'village.evacuate_on_zone_attack': 'Trigger preemptive evacuation of fragile units (axe, noble) when zone neighbors are under attack — requires evacuate_fragile_units_on_attack: true (Feature 12)',
    'village.zone_attack_threshold': 'Minimum number of zone neighbors that must be under attack simultaneously to trigger preemptive evacuation (Feature 12)',
    'hunter': 'Agendamento de ataques coordenados com chegada simultânea (Feature 10) — gerencie pela página /hunter',
    'hunter.enabled': 'Ativar o Hunter — quando true, o bot verifica e dispara os schedules a cada ciclo',
    'zones': 'Agrupamento geográfico de aldeias em zonas por proximidade (Feature 11)',
    'zones.enabled': 'Ativar o sistema de zonas geográficas',
    'zones.radius': 'Raio em campos para agrupar aldeias na mesma zona (padrão: 10)',
    'pvp_conquest': 'Agendamento semi-manual de conquistas PvP com scout + simulação + Hunter (Feature 13)',
    'pvp_conquest.enabled': 'Ativar o módulo de conquista PvP',
    'pvp_conquest.clear_ratio': 'Fração das tropas da aldeia ofensiva usada no clear (ex: 0.8 = 80%)',
    'pvp_conquest.min_attack_power': 'Poder de ataque mínimo (soma ATT × quantidade) para considerar o clear viável',
    'pvp_conquest.nobles_per_target': 'Número máximo de nobles a enviar por alvo',
    'pvp_conquest.arrival_buffer_seconds': 'Segundos de antecedência do clear em relação aos nobles',
    'pvp_conquest.scout_amount': 'Número de espiões usados no scout inicial do alvo',
}

buildings = ["main", "barracks", "stable", "watchtower", "smith", "garage", "place", "statue", "market", "wood",
             "stone", "iron", "farm", "hide", "wall", "snob", "church"]

# Sections that contain nested dicts and need special rendering in the config UI
nested_sections = ["conquest", "resource_sharing", "inheritance", "empire", "profile_templates", "pvp_conquest"]
