help_file = {
    'server': 'Configure the world the bot should play on',
    'server.server': 'The server endpoint to use (the world)',
    'server.endpoint': 'Endpoint server to use (the full url)',
    'server.server_on_twstats': 'Is the server listed on twstats.com?',
    'reporting': 'Enable advanced reporting features',
    'reporting.enabled': 'Enable the reporting feature',
    'reporting.connection_string': 'Could be of type file://filename or mysql://user:password@host:port/database_name',
    'bot': 'Set global bot configuration variables',
    'bot.active_hours': 'The hours when the bot should be active, e.g. "6-23" (does not impact attack timings)',
    'bot.delay_factor': 'Delay factor to use — 5-7 seconds * delay factor (very low factors will probably cause ban)',
    'bot.active_delay': 'Delay in seconds to use during active hours',
    'bot.inactive_delay': 'Delay in seconds to use during inactive hours',
    'bot.inactive_still_active': 'When disabled, stops the bot from running during inactive hours',
    'bot.add_new_villages': 'Automatically add the default village config to newly conquered villages',
    'bot.village_name_template': 'Template to use for new villages — use {num} to set the config index as name',
    'bot.village_name_number_length': 'The number length — lower values will be prefixed with zeroes',
    'bot.auto_set_village_names': 'Automatically set village names based on the template',
    'bot.user_agent': 'Set this to the browser agent your session is using (mismatch may cause ban)',
    'bot.max_cached_reports': 'Maximum number of files kept in cache/reports — the oldest are pruned once the limit is exceeded. Keeps the per-cycle farm/report cross-check bounded. 0 disables pruning',
    'bot.humanize_village_order': 'Shuffle the village processing order every cycle instead of always following the same sequence (Feature 23)',
    'bot.jitter_min': 'Lower bound (seconds) of the random jitter added to every cycle delay (Feature 23)',
    'bot.jitter_max': 'Upper bound (seconds) of the random jitter added to every cycle delay (Feature 23)',
    'bot.attention_lag_chance': 'Probability (0.0-1.0) per cycle of an extra-slow "distracted player" delay. 0 disables it. Never triggers while a managed village is under attack (Feature 23)',
    'bot.attention_lag_extra_min': 'Minimum extra seconds added to the cycle delay when the attention-lag roll succeeds (Feature 23)',
    'bot.attention_lag_extra_max': 'Maximum extra seconds added to the cycle delay when the attention-lag roll succeeds (Feature 23)',
    'building': 'Automatic construction of buildings',
    'building.manage_buildings': 'Automatically manage buildings',
    'building.default': 'The default build template to use — village configs override this',
    'building.max_lookahead': 'Max number of items in queue to check before stopping',
    'building.max_queued_items': 'Max queued items (default: 2, premium: 5)',
    'building.auto_queue_len': 'When enabled and world.premium_account is detected as true, automatically use building.premium_max_queued_items instead of building.max_queued_items (Feature 22)',
    'building.premium_max_queued_items': 'Queue length used instead of max_queued_items when auto_queue_len is enabled and the account is premium (Feature 22)',
    'units': 'Automatic recruitment and upgrade of units',
    'units.recruit': 'Automatically recruit units',
    'units.upgrade': 'Automatically upgrade units (level 1-3 and 1-10 smith systems)',
    'units.default': 'Default template for unit recruitment (templates/troops)',
    'units.batch_size': 'Amount of units to attempt to create per run — increase in late-game',
    'units.manage_defence': 'Manage defence distribution between villages (experimental)',
    'units.remove_manual_queued': 'Remove manually queued recruitment entries',
    'units.randomize_unit_queue': 'Randomize unit queue for a wider variety of units',
    'farms': 'Automatic farming of nearby (barbarian) villages',
    'farms.farm': 'Enable automatic farming',
    'farms.min_points': 'Minimum points of villages to attack',
    'farms.max_points': 'Maximum points of villages to attack',
    'farms.search_radius': 'Max radius of villages to attack (fields)',
    'farms.default_away_time': 'Default cooldown in seconds before attacking a village again',
    'farms.full_loot_away_time': 'Cooldown for villages with high resource gain',
    'farms.low_loot_away_time': 'Cooldown for villages with low resource gain',
    'farms.max_farms': 'Number of nearby villages to check for farming',
    'farms.attack_higher_points': 'If disabled, villages with higher points than the current one are ignored',
    'farms.force_scout_if_available': 'Only attack villages that have been attacked before or scouted first',
    'farms.farm_scout_amount': 'Number of spies used to scout a village before farming',
    'market': 'Automatic management of public market trading (offer system)',
    'market.auto_trade': 'Enable automated public market trading',
    'market.max_trade_duration': 'Max duration of public trade offers (hours)',
    'market.auto_remove': 'Automatically remove existing or expired trade offers',
    'market.trade_multiplier': 'Enable uneven trade ratios (if supported by the world)',
    'market.trade_multiplier_value': 'Trade multiplier value — lower means more gain',
    'market.trade_max_per_hour': 'Max number of trades the bot can do in 1 hour',
    'resource_sharing': 'Automatic direct resource transfer between your own villages (Feature 9)',
    'resource_sharing.enabled': 'Enable automatic resource sharing between managed villages',
    'resource_sharing.priority': 'Priority mode for need-based transfers — "new_villages" sends to the lowest-point villages first, anything else sends to the largest deficit first',
    'resource_sharing.max_sends_per_cycle': 'Max number of separate transfers a single village may start per cycle',
    'resource_sharing.min_send_amount': 'Transfers smaller than this (per resource) are not worth a merchant trip and are skipped',
    'resource_sharing.receiver_fill_max_pct': 'Never fill a receiving village above this percentage of its storage — leaves margin for the production that keeps running during travel time',
    'resource_sharing.merchant_capacity': 'Resources carried per merchant (1000 on worlds without a merchant bonus — check <MerchantBonus> in the public world config)',
    'resource_sharing.overflow_enabled': 'Rule 1 — rescue resources from a village whose warehouse is about to overflow',
    'resource_sharing.overflow_trigger_pct': 'A resource above this percentage of the village own storage counts as overflowing (e.g. 85 = 85%)',
    'resource_sharing.overflow_target_pct': 'When rescuing an overflow, send away enough to bring the resource back down to this percentage',
    'resource_sharing.need_enabled': 'Rule 2 — supply villages that are blocked on resources for their build/recruit queue',
    'resource_sharing.need_donor_floor': 'Absolute amount of a resource a village keeps for itself before donating under rule 2. Absolute on purpose — a percentage of own storage makes big-warehouse villages permanently ineligible to donate',
    'conquest': 'Automated barbarian village conquest (Feature 8)',
    'conquest.enabled': 'Enable automated conquest — activate only when nobles are available',
    'conquest.max_radius': 'Maximum radius in fields to search for conquest targets',
    'conquest.priority': 'Target selection priority — "fill_gaps" scores by centrality, distance and points',
    'conquest.min_points': 'Minimum points a target village must have to be considered',
    'conquest.max_points': 'Maximum points a target village can have to be considered',
    'conquest.loyalty_regen_per_hour': 'Loyalty regeneration per hour. Per-world value published at /page/settings ("Aumento de lealdade por hora") — read it there, do not guess. br143 = 1',
    'conquest.loyalty_drop_per_noble': 'FALLBACK ONLY — the bot reads the real range from the world itself (<mood> loss_min/loss_max in interface.php?func=get_config, same numbers /page/settings shows as "Redução de lealdade por ataque do nobre"; br143 = 20-35) and plans against the worst case. This key is only used when the world did not publish the block. Note the drop is a RANGE, not a value: a 4-noble train removes 80 to 140, not a guaranteed 100',
    'conquest.escort_ratio': 'Fraction of available troops to send as noble train escort (e.g. 0.5 = 50%)',
    'conquest.min_escort': 'Minimum escort units per unit type (optional override)',
    'conquest.min_escort_total': 'Minimum combined escort troops per noble attack, regardless of unit type (default: 50)',
    'conquest.escort_reserve_max_pct': 'Maximum fraction of any single unit type that may be reserved while waiting for the escort to build up (default: 0.8). Below 1.0 a residual always stays available to farm and gather — 1.0 restores the old behaviour of reserving up to 100% of a type',
    'conquest.escort_reserve_min_progress': 'Only start reserving troops for the escort once this fraction of the required total is already home (default: 0.5). Far from the target the reserve just freezes the farm income that funds recruitment, so it is skipped — 0.0 restores the old always-reserve behaviour',
    'inheritance': 'Config inheritance mode for newly conquered villages (Feature 6)',
    'inheritance.mode': 'Inheritance mode: "empire_ratio" (profile-aware), "nearest_village" (closest donor), "global_template" (original behaviour)',
    'empire': 'Empire-wide offensive/defensive village ratio (Feature 7). Villages with the "watchtower" profile are excluded from this count entirely (Feature 30)',
    'empire.offensive_ratio': 'Offensive side of the ratio. With offensive_ratio 1 and defensive_ratio 3 the empire targets 1 offensive village for every 3 defensive ones',
    'empire.defensive_ratio': 'Defensive side of the ratio (default 3, i.e. a defensive-leaning empire)',
    'watchtower': 'Territorial allocation of watchtower villages (Feature 30). A watchtower village is defensive by nature but is allocated by geography, not by the empire ratio — so it is excluded from the empire count. Requires the world to actually have the watchtower building',
    'watchtower.enabled': 'Allow the bot to designate newly conquered villages as ADDITIONAL watchtower villages. The first tower is never created automatically — pick an established, central village by hand and set its profile to "watchtower". Leave false on worlds without the watchtower building',
    'watchtower.min_spacing': 'Minimum distance in tiles between two watchtower villages. A conquered village farther than this from every existing tower becomes a tower itself. Default 16, just above the level-20 radius of 15.0 tiles — larger values collapse the warning time at the seams (at 26 tiles, the worst point is tagged the instant the attack lands); see docs/watchtower.md',
    'watchtower.min_villages': 'Do not designate any watchtower village until the empire has at least this many villages. Guards a young account against converting an early village into a tower it cannot afford',
    'profile_templates': 'Per-profile config applied to every newly conquered village (Feature 7). These keys always override whatever was inherited from the donor village, so put here anything that *defines* the profile',
    'profile_templates.offensive': 'Keys forced on villages assigned the "offensive" profile',
    'profile_templates.defensive': 'Keys forced on villages assigned the "defensive" profile (e.g. support_others, so defensive villages send support by default)',
    'profile_templates.watchtower': 'Keys forced on villages assigned the "watchtower" profile (Feature 30)',
    'world': 'World-specific feature flags',
    'world.knight_enabled': 'The world has knights enabled',
    'world.flags_enabled': 'Allows automatic management of flags (upgrading and defence)',
    'world.quests_enabled': 'World has quests enabled (bot will automatically finish them)',
    'world.trade_for_premium': 'World has the premium market enabled (doing this too much could result in ban)',
    'world.archers_enabled': 'Are archers / marchers enabled on the world',
    'world.building_destruction_enabled': 'Are rams / catapults enabled on the world',
    'world.premium_account': 'Auto-detected premium account status (from the overview page). Set manually to override detection (Feature 22)',
    'village_template': 'Default template applied to all newly managed villages',
    'village.building': 'Override build template for this village',
    'village.units': 'Override recruitment / farm template for this village',
    'village.managed': 'This village should be managed by the bot',
    'village.active_hours': 'Active hours override for this village (e.g. "8-22") — null uses global setting',
    'village.delay_factor': 'Request delay factor override for this village — null uses the global bot.delay_factor (Feature 23)',
    'village.keep_resources': 'Amounts this village keeps for itself before donating under the resource sharing need rule, e.g. {"stone": 30000} while saving for a noble. Raises resource_sharing.need_donor_floor for this village only; does not hold back overflow, which would be wasted anyway',
    'village.profile': 'Village combat profile: "offensive" or "defensive" — set automatically by empire ratio',
    'village.additional_farms': 'List of village IDs to include in the farming process',
    'village.prioritize_building': 'Do not recruit if the builder does not have enough resources',
    'village.prioritize_snob': 'Do not recruit if the noble queue does not have enough resources',
    'village.trade_for_premium': 'Trade left-over resources for premium points (requires global option)',
    'village.gather_enabled': 'Use left-over units to gather additional resources',
    'village.gather_selection': 'The gather operation to perform (must be unlocked first)',
    'village.snobs': 'Number of nobles to maintain in this village',
    'village.mint_coins': 'Mint gold coins without ever recruiting a noble (only applies when snobs is 0). Coins belong to the account, nobles cost this village\'s population - this is what a watchtower village should do. Only mints from surplus - the priority order is buildings, then troops, then coins: it never mints while the build queue still lacks resources or while the village is below its troop template (support losses included), and it never requests resources from the market',
    'village.evacuate_fragile_units_on_attack': 'Automatically evacuate fragile units (axe, noble) to nearby safe villages when under attack',
    'village.support_others': 'Allow sending automatic support to allied villages',
    'village.support_others_factor': 'Fraction of defensive units to use in support operations',
    'village.support_others_max_villages': 'Max number of villages to send support to',
    'village.request_support_on_attack': 'Automatically request support units when under attack',
    'village.conquest_enabled': 'Enable conquest actions from this village — overrides global conquest.enabled',
    'village.evacuate_on_zone_attack': 'Trigger preemptive evacuation of fragile units (axe, noble) when zone neighbors are under attack — requires evacuate_fragile_units_on_attack: true (Feature 12)',
    'village.zone_attack_threshold': 'Minimum number of zone neighbors that must be under attack simultaneously to trigger preemptive evacuation (Feature 12)',
    'village.evacuate_urgency_threshold_sec': 'Only actually evacuate when the soonest incoming command is within this many seconds of arriving (default 1800 = 30 min) — farther-out commands just keep the defence flag active (Feature 16)',
    'hunter': 'Agendamento de ataques coordenados com chegada simultânea (Feature 10) — gerencie pela página /hunter',
    'hunter.enabled': 'Ativar o Hunter — quando true, o bot verifica e dispara os schedules a cada ciclo',
    'zones': 'Agrupamento geográfico de aldeias em zonas por proximidade (Feature 11)',
    'zones.enabled': 'Ativar o sistema de zonas geográficas',
    'zones.radius': 'Raio em campos para agrupar aldeias na mesma zona (padrão: 10)',
    'pvp_conquest': 'Agendamento semi-manual de conquistas PvP com scout + simulação + Hunter (Feature 13)',
    'pvp_conquest.enabled': 'Ativar o módulo de conquista PvP',
    'pvp_conquest.clear_ratio': 'Fração das tropas da aldeia ofensiva usada no clear (ex: 0.8 = 80%)',
    'pvp_conquest.min_attack_power': 'Poder de ataque mínimo (soma ATT × quantidade) para considerar o clear viável',
    'pvp_conquest.nobles_per_target': 'Número máximo de nobles a enviar por alvo',
    'pvp_conquest.arrival_buffer_seconds': 'Segundos de antecedência do clear em relação aos nobles',
    'pvp_conquest.scout_amount': 'Número de espiões usados no scout inicial do alvo',
    'pvp_conquest.dynamic_moral_night_bonus': 'Calcula moral (por pontos atacante/defensor) e night bonus (horário + world settings) reais no simulador, em vez de valores neutros fixos (moral=100, sem night bonus). Estimativa best-effort — valide contra o simulador do próprio jogo antes de confiar totalmente (ver docs/game_comparison.md item 1)',
    'statue': 'Leitura periódica do estado do(s) Paladino(s) via screen=statue (Feature 24, fase 1 — só leitura, sem automação)',
    'statue.enabled': 'Ativar a leitura periódica do estado do Paladino (nível, XP, skills, slots) e persistência em cache/statue/status.json para exibição em /statue',
    'inventory': 'Leitura periódica do inventário (Perfil > Inventário) via screen=inventory (Feature 25, fase 1 — só leitura, nenhum item é ativado)',
    'inventory.enabled': 'Ativar a leitura periódica do inventário (itens, quantidades, descrições, validade) e persistência em cache/inventory/status.json para exibição em /inventory. Custa duas requisições por ciclo: o HTML da tela (rótulos de tipo/categoria) e o AJAX get_inventory (os itens)',
}

buildings = ["main", "barracks", "stable", "watchtower", "smith", "garage", "place", "statue", "market", "wood",
             "stone", "iron", "farm", "hide", "wall", "snob", "church"]

# Sections that contain nested dicts and need special rendering in the config UI
nested_sections = ["conquest", "resource_sharing", "inheritance", "empire", "watchtower", "profile_templates", "pvp_conquest"]
